services:
  discord:
    build: .
    container_name: imabot
    image: imabot
    environment:
      DISCORD_TOKEN: '<DISCORD_TOKEN>'
      OVH_APPLICATION_KEY: '<OVH_APPLICATION_KEY>'
      OVH_APPLICATION_SECRET: '<OVH_APPLICATION_SECRET>'
      OVH_CONSUMER_KEY: '<OVH_CONSUMER_KEY>'
      PYTHONIOENCODING: 'UTF-8'
      PYTHONUNBUFFERED: 'True'
      DISCORD_ROLE_TECH_RO: 'Tech'
      DISCORD_ROLE_TECH_RW: 'Tech Lead'
      DISCORD_ROLE_ACCOUNTING: 'Accounting'
      ANSIBLE_HOST_KEY_CHECKING: 'False'