services:
  discord:
    build: .
    container_name: imabot
    image: imabot
    environment:
      DISCORD_TOKEN: '<DISCORD_TOKEN>'
      OVH_APPLICATION_KEY: '<OVH_APPLICATION_KEY>'
      OVH_APPLICATION_SECRET: '<OVH_APPLICATION_SECRET>'
      OVH_CONSUMER_KEY: '<OVH_CONSUMER_KEY>'